name: build

on:
  push:
    branches: [refactor, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test, Lint, and Build
        run: |
          make ci
      - name: Generate docs.
        run: |
          make docs
      - name: Archive generated docs for gh pages.
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

